version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: futicrit
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    restart: always
    networks:
      - futicrit_network

networks:
  futicrit_network:
    driver: bridge
